// src/runtime/index.js
const { RuntimeAPI } = require('./RuntimeAPI');
const { parse }      = require('../parser');
const crypto         = require('crypto');
const fs             = require('fs');
const path           = require('path');

// ── Load kernel private key ───────────────────────────────────────────────────
// FIX: Load at module initialisation time (when kernel boots) instead of
// lazily on the first execute() call. This prevents a 5-10s delay on the
// first request caused by RSA key file I/O + audit chain signing overhead.
// ─────────────────────────────────────────────────────────────────────────────

function _loadPrivateKey() {
  const keyPath      = process.env.KERNEL_PRIVATE_KEY_PATH || './kernel-keys/kernel-private.pem';
  const absolutePath = path.isAbsolute(keyPath)
    ? keyPath
    : path.join(process.cwd(), keyPath);

  if (!fs.existsSync(absolutePath)) {
    console.warn('[kernel] Warning: Private key not found at', absolutePath);
    console.warn('[kernel] Audit entries will NOT be signed');
    return null;
  }

  const key = fs.readFileSync(absolutePath, 'utf8');
  console.log('[kernel] ✅ Private key loaded for signing');
  return key;
}

// Loaded once at require() time — cached for all subsequent execute() calls
const KERNEL_PRIVATE_KEY = _loadPrivateKey();

function _loadPublicKey() {
  if (!KERNEL_PRIVATE_KEY) return null;
  try {
    const pubKeyPath      = process.env.KERNEL_PUBLIC_KEY_PATH || './kernel-keys/kernel-public.pem';
    const absolutePubPath = path.isAbsolute(pubKeyPath)
      ? pubKeyPath
      : path.join(process.cwd(), pubKeyPath);

    if (!fs.existsSync(absolutePubPath)) return null;

    return fs.readFileSync(absolutePubPath, 'utf8')
      .replace('-----BEGIN PUBLIC KEY-----', '')
      .replace('-----END PUBLIC KEY-----', '')
      .replace(/\s/g, '');
  } catch (err) {
    console.warn('[kernel] Could not load public key:', err.message);
    return null;
  }
}

// Also loaded once at require() time
const KERNEL_PUBLIC_KEY = _loadPublicKey();

// ── Sign audit data with RSA-SHA256 ──────────────────────────────────────────
// Uses RSA-SHA256 to match the RSA key generated by crypto.generateKeyPairSync.
// The same sorted JSON serialization is used during verification.

function signAuditData(auditData, privateKeyPem) {
  if (!privateKeyPem) return null;

  try {
    // Serialize with sorted keys — must match verifySignature() in server.js
    const serialized = JSON.stringify(auditData, Object.keys(auditData).sort());

    const sign = crypto.createSign('SHA256');
    sign.update(serialized);
    sign.end();

    return sign.sign(privateKeyPem, 'hex');
  } catch (err) {
    console.error('[kernel] Signature error:', err.message);
    return null;
  }
}

// ── Main execute function ─────────────────────────────────────────────────────

async function execute(workflow, inputs, agentResolver, verbose = false) {
  const rt = new RuntimeAPI({ verbose });

  // Run the workflow — result contains only Return values
  const result = await rt.executeWorkflow(workflow, inputs, agentResolver);

  // Grab audit data while RuntimeAPI instance is still alive
  const lastEntry  = rt.auditLog.at(-1);
  const firstEntry = rt.auditLog.at(0);

  // Build audit object BEFORE signing — must match verifySignature() structure
  const auditData = {
    execution_hash:          lastEntry?.hash          ?? null,
    previous_hash:           firstEntry?.hash         ?? 'GENESIS',
    merkle_root:             rt._calculateMerkleRoot(),
    kernel_version:          lastEntry?.details?.kernel_version          ?? null,
    governance_profile_hash: lastEntry?.details?.governance_profile_hash ?? null,
    integrity:               rt.verifyAuditLogIntegrity(),
    chain:                   rt.auditLog,
  };

  // FIX: Use pre-loaded keys — no file I/O on hot path
  const signature = signAuditData(auditData, KERNEL_PRIVATE_KEY);

  // Attach audit to result — server.js detaches it before sending to client
  result.__audit = {
    ...auditData,
    signature,        // RSA-SHA256 hex signature
    publicKey: KERNEL_PUBLIC_KEY, // Stripped PEM for client verification
  };

  return result;
}

// ── Standalone PII redaction helper ──────────────────────────────────────────
// Exposes kernel redaction without running a full workflow.
// Usage: const { redacted, redactions } = redact(userInput);

function redact(text) {
  const rt = new RuntimeAPI({ verbose: false });
  return rt.redact(text);
}

module.exports = { execute, parse, redact };